baseURL = 'http://repton-projects.org/'
languageCode = 'en-us'
title = 'Repton Projects'

[permalinks]
  blog = "/:title/"

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "why-project-on-demand"
    name = "Why Project on Demand?"
    url = "/why-project-on-demand"
    weight = 2

[[menu.main]]
    identifier = "features"
    name = "Explore Features"
    url = "/features"
    weight = 3

